server.port: 8080

# 日志
logging:
  level:
    root: info
    com.baomidou.mybatisplus: info
    com.asiainfo.crm: debug
    com.asiainfo.bits: debug
    com.ai.aif.csf: info


spring:
  datasource:
    atomikos:
      base:
        uniqueResourceName: base
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//10.13.3.19:1521/NEWHNPDB
        user: UOP_BASE
        password: UOP_BASE
        minPoolSize: 2
        maxPoolSize: 5
        maxIdleTime: 60
        maxLifetime: 1200
        maintenanceInterval: 60

  jta:
    atomikos:
      properties:
        log-base-name: base-tmlog
        default-jta-timeout: 60000
        log-base-dir: ../logs
    transaction-manager-id: tx

  cache:
    # 指定缓存类型: none(禁用缓存), simple(用于开发), redis（用于生产）
    type: simple

  session:
    # session 的存储方式，开发模式（本地）：none，生产模式（分布式缓存）：redis
    store-type: none
    timeout: 1800

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: DELETED
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    default-fetch-size: 512
